version: '3.5'
services:


# # ============================================================================
# # ============================================================================
    # #                         HELYOS AGENT 
# # ============================================================================
# # ============================================================================


    agent_simulator:
        # image: helyosframework/helyos_agent_slim_simulator:0.3.0
        build: ../

        volumes:
            - ./custom-geometry.json:/app/geometry.json
            
        environment:

            # AGENT ID
            - UUID=Bb3402-9fc5-fdgs-434b-b87e-f19c5435113 
            - PATH_TRACKER=perfect  # perfect | straight_to_destination | stanley
            - ASSIGNMENT_FORMAT=autotruck-path  # fixed | trajectory | destination | autotruck-path |
            - NAME='MY TRUCK'
            - X0=0
            - Y0=-50000
            - ORIENTATION=0
            - VELOCITY=1.8 
            - VEHICLE_PARTS=2
            - YARD_UID=1

            # RABBITMQ 
            - ENCRYPT=none  # none | agent | helyos | helyos-agent
            - RABBITMQ_HOST=local_message_broker # local_message_broker | rabbitmq.ivi.fraunhofer.de 
            - RABBITMQ_PORT=5672

            # RBMQ ACCOUNT
            - RBMQ_USERNAME=${HELYOS_RBMQ_USERNAME}
            - RBMQ_PASSWORD=${HELYOS_RBMQ_PASSWORD}
            # OR
            - REGISTRATION_TOKEN=0000-0000-0000-0000-0000

        networks:
            - control-tower-net
               



networks:
    control-tower-net:
        name: api-network
        external: true



