version: '3.5'
services:


# # ============================================================================
# # ============================================================================
    # #                         HELYOS AGENT 
# # ============================================================================
# # ============================================================================


    agent_simulator:
        # image: helyosframework/helyos_agent_slim_simulator:0.3.0
        build: ../

        volumes:
            - ./custom-geometry.json:/app/geometry.json        # To modify reported geometry.
            - ./ca_certificate.pem:/app/ca_certificate.pem # To verify rbmq server url.
        environment:

            # AGENT ID
            - UUID=Bb3402-9fc5-fdgs-434b-b87e-f19c5435113 
            - PATH_TRACKER=ideal  # ideal | straight_to_destination | stanley (defaults to ideal)
            - ASSIGNMENT_FORMAT=autotruck-path  # fixed | trajectory | destination | autotruck-path 
            - NAME='MY TRUCK'
            - X0=0
            - Y0=-50000
            - ORIENTATION=0
            - VELOCITY=1.8 
            - VEHICLE_PARTS=2
            - YARD_UID=1

            # RABBITMQ 
            - RBMQ_HOST=local_message_broker # local_message_broker | rabbitmq.server.com 

            # FOR MQTT AGENT
            # - RBMQ_PORT=8883
            # - ENABLE_SSL=True # True | False (defaults to False)
            # - PROTOCOL=MQTT # AMQP | MQTT (defaults to AMQP)
            
            # FOR AMQP AGENT (DEFAULT)
            - RBMQ_PORT=5671
            - ENABLE_SSL=True # True | False (defaults to False)
            - PROTOCOL=AMQP # AMQP | MQTT (defaults to AMQP)

            # RBMQ ACCOUNT
            - RBMQ_USERNAME=Bb3402-9fc5-fdgs-434b-b87e-f19c5435113
            - RBMQ_PASSWORD=senha
            # OR
            # - REGISTRATION_TOKEN=0000-0000-0000-0000-0000

        networks:
            - control-tower-net
               



networks:
    control-tower-net:
        name: api-network
        external: true



